
# input and Output pathways used in StartProcesses
LOCATIONOFYOURPROJECT =
OUTPUTFILELOCATION =
INPUTFILESLOCATION =



# HtmlScripts and filePaths used in views.py
LOCATIONBASHSCRIPTHUMAN =
LOCATIONBASHSCRIPTKNEADDATA =
LOCATIONBASHSCRIPTCOMPLEETPIPELINE =
LOCATIONUNIPROTDATABASE =


FASTQCIMGFOLDER =

# uploaded filepath

LOCATIONUPLOADEDFILES =

#databases
LOCATIONUNIREFFPULLDATABASE =
LOCATIONCHOCOPHLANDATABASE =
LOCATIONSILVADATABASE =
LOCATIONTRIMMOMATICDATABASE =