# Generated by Django 4.0.4 on 2022-04-19 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=15)),
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('initials', models.CharField(max_length=4)),
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('departments', models.ManyToManyField(to='biobakery.department')),
            ],
        ),
        migrations.CreateModel(
            name='Researches',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('researches_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biobakery.department')),
            ],
        ),
    ]
