# Generated by Django 4.0.4 on 2022-04-19 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biobakery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researches',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biobakery.users'),
        ),
    ]
